### ISSUE TITLE
Blog Avatar

### ISSUE THREAD

**Issue by ltfi** [gokhanettin/gokhanettin.github.io#1]
Please change your blog picture (avatar), the picture is making a non-professional impression, just a comment.

**Comment by gokhanettin** [comment]
Agreed. I should also have picked a professional impression maker bird as my avatar. My avatar might give a non-professional impression to those who have no appreciation for such a hand-crafted avatar. :confused: My avatar is an effort of a friend of mine and I promised to keep it as my online face. :smile:

**Comment by ltfi** [comment]
Thank you for your kind explanation.
